### PR TITLE
Update install scripts

### PR DESCRIPTION
**Pull request by rowleya**
Some changes to the install scripts that I found useful.  This also removes PyNN7.

This is a PR as requested, as it changes automatic_make.

### CODE REVIEW

**Comment by rowleya** [comment]
I don't think this changes from the original version which also used "source"

**Comment by andrewgait** [comment]
> I don't think this changes from the original version which also used "source"

It does in one important detail: the "source" command is now on the same line as the cd commands; if the "source" command fails, which it does in some shells, then the final cd command on that line doesn't happen and the script moves to the next line.

**Comment by rowleya** [comment]
OK - that made me spot an error (those calls shouldn't be needed).  Fixing now...

**Comment by rowleya** [comment]
OK, hopefully fixed now

**Comment by rowleya** [comment]
Oops, merged a bit too well!

**Comment by rowleya** [comment]
That should fix it now

**Pull request merged**
